name: OpenNoteTaker
options:
  bundleIdPrefix: com.moonshine
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  Moonshine:
    path: ../../../swift

targets:
  OpenNoteTaker:
    type: application
    platform: macOS
    sources:
      - path: Sources/OpenNoteTaker
    dependencies:
      - package: Moonshine
        product: Moonshine
    settings:
      SWIFT_VERSION: "6.0"
      PRODUCT_NAME: OpenNoteTaker
      PRODUCT_BUNDLE_IDENTIFIER: com.moonshine.OpenNoteTaker
      INFOPLIST_FILE: Info.plist
      INFOPLIST_KEY_NSHumanReadableCopyright: ""
      INFOPLIST_KEY_CFBundleDisplayName: OpenNoteTaker
      INFOPLIST_KEY_CFBundleName: OpenNoteTaker
      INFOPLIST_KEY_NSPrincipalClass: NSApplication
      INFOPLIST_KEY_NSHighResolutionCapable: true
      ENABLE_HARDENED_RUNTIME: true
      CODE_SIGN_ENTITLEMENTS: OpenNoteTaker.entitlements
      MACOSX_DEPLOYMENT_TARGET: "13.0"
    info:
      path: Info.plist
      properties:
        LSMinimumSystemVersion: "13.0"
        NSMicrophoneUsageDescription: "OpenNoteTaker needs microphone access to transcribe your conversations."
        NSScreenCaptureUsageDescription: "OpenNoteTaker needs screen recording permission to capture system audio from Zoom and other meeting applications."

schemes:
  OpenNoteTaker:
    build:
      targets:
        OpenNoteTaker: all
    run:
      config: Debug
      executable: OpenNoteTaker

