// Proves every model we ship can create a session under the linked ORT.
//
// This is the test that catches a minimal build missing an operator. A minimal
// ORT drops every kernel not named in
// core/third-party/onnxruntime/moonshine-required-operators.config, and a model
// needing an absent one fails at session creation with "Could not find an
// implementation for <op>". Nothing detects that at build time, and on a normal
// desktop build with the full runtime nothing detects it at all — which is why
// this test also has to run on the platforms that link the minimal library
// (wasm, iOS, Android), not just here.
//
// It loads and discards, running no inference: the question is whether the
// kernels exist, and answering it for the whole catalog is fast.
//
// The embedded models are the ones worth being careful about. They are neither
// files on disk nor catalog downloads, they are C arrays compiled into the
// library, so a config generated by walking the data directory omitted them and
// the resulting wasm build failed at runtime on a Relu the voice detector
// needed. generate-ort-op-config.py now finds them by scanning for the ORT file
// magic; this checks the result.
//
// scripts/test-core.sh runs it against the desktop runtime, which is the weak
// case: a full ORT has every kernel and can only fail on a corrupt file. To
// run it where it means something, build it for the target and point
// MOONSHINE_MODEL_ROOT at a checkout. On the iOS simulator:
//
//   cmake -S core -B /tmp/sweep-sim -G Xcode -DCMAKE_SYSTEM_NAME=iOS \
//       -DCMAKE_OSX_SYSROOT=iphonesimulator -DCMAKE_OSX_ARCHITECTURES=arm64 \
//       -DCMAKE_OSX_DEPLOYMENT_TARGET=15.1 \
//       -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO
//   cmake --build /tmp/sweep-sim --config Release --target ort-load-sweep-test
//   SIMCTL_CHILD_MOONSHINE_MODEL_ROOT="$PWD" xcrun simctl spawn booted \
//       /tmp/sweep-sim/Release-iphonesimulator/ort-load-sweep-test.app/ort-load-sweep-test
//
// On an Android emulator, with $NDK set, push the models (2.6 GB, a few
// seconds) beside the binary and the library:
//
//   cmake -S core -B /tmp/sweep-android -DANDROID_ABI=arm64-v8a \
//       -DANDROID_PLATFORM=android-26 -DCMAKE_BUILD_TYPE=Release \
//       -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake
//   cmake --build /tmp/sweep-android --target ort-load-sweep-test
//   adb push core/moonshine-tts/data /data/local/tmp/sweep/core/moonshine-tts/data
//   adb push test-assets /data/local/tmp/sweep/test-assets
//   adb push /tmp/sweep-android/ort-load-sweep-test \
//       core/third-party/onnxruntime/lib/android/arm64/libonnxruntime.so \
//       /data/local/tmp/sweep/
//   adb shell 'cd /data/local/tmp/sweep && LD_LIBRARY_PATH=. \
//       MOONSHINE_MODEL_ROOT=. ./ort-load-sweep-test'

#include <onnxruntime_c_api.h>

#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <set>
#include <string>
#include <vector>

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"
#include "silero-vad-model-data.h"

namespace fs = std::filesystem;

namespace {

const OrtApi *api() { return OrtGetApiBase()->GetApi(ORT_API_VERSION); }

/// Discards a status we have no way to act on.
///
/// Setting a session option cannot meaningfully fail here, and the caller is
/// about to find out anyway when the session does not open.
void ignore_status(OrtStatus *status) {
  if (status != nullptr) {
    api()->ReleaseStatus(status);
  }
}

struct OrtEnvHandle {
  OrtEnv *env = nullptr;
  OrtEnvHandle() {
    ignore_status(api()->CreateEnv(ORT_LOGGING_LEVEL_ERROR, "load-sweep", &env));
  }
  ~OrtEnvHandle() {
    if (env != nullptr) {
      api()->ReleaseEnv(env);
    }
  }
  OrtEnvHandle(const OrtEnvHandle &) = delete;
  OrtEnvHandle &operator=(const OrtEnvHandle &) = delete;
};

/// Session options matching how the library loads models.
///
/// load_model_format=ORT is the point: it makes a stray .onnx fail here on a
/// full build exactly as it would on a minimal one.
OrtSessionOptions *make_options() {
  OrtSessionOptions *opts = nullptr;
  ignore_status(api()->CreateSessionOptions(&opts));
  ignore_status(
      api()->SetSessionGraphOptimizationLevel(opts, ORT_ENABLE_EXTENDED));
  ignore_status(
      api()->AddSessionConfigEntry(opts, "session.load_model_format", "ORT"));
  ignore_status(api()->SetIntraOpNumThreads(opts, 1));
  return opts;
}

/// The failure reason, or an empty string on success.
std::string session_error(OrtEnv *env, const fs::path &model) {
  OrtSessionOptions *opts = make_options();
  OrtSession *session = nullptr;
  OrtStatus *status =
      api()->CreateSession(env, model.c_str(), opts, &session);
  std::string message;
  if (status != nullptr) {
    message = api()->GetErrorMessage(status);
    api()->ReleaseStatus(status);
  }
  if (session != nullptr) {
    api()->ReleaseSession(session);
  }
  api()->ReleaseSessionOptions(opts);
  return message;
}

std::string session_error_from_memory(OrtEnv *env, const void *data,
                                      size_t length) {
  OrtSessionOptions *opts = make_options();
  OrtSession *session = nullptr;
  OrtStatus *status =
      api()->CreateSessionFromArray(env, data, length, opts, &session);
  std::string message;
  if (status != nullptr) {
    message = api()->GetErrorMessage(status);
    api()->ReleaseStatus(status);
  }
  if (session != nullptr) {
    api()->ReleaseSession(session);
  }
  api()->ReleaseSessionOptions(opts);
  return message;
}

/// Model roots to sweep.
///
/// The bundled TTS data and whatever the download tests have fetched into
/// test-assets, which is where the catalog models land. Named rather than
/// discovered so the sweep does not depend on the working directory beyond
/// finding the repository, and so it never wanders into a build tree full of
/// copies of models it has already loaded.
///
/// MOONSHINE_MODEL_ROOT points it at a repository elsewhere, which is how the
/// minimal builds get swept: an iOS simulator binary run under `simctl spawn`
/// starts at /, and an Android binary sees only what was pushed to the device.
std::vector<fs::path> model_roots() {
  std::vector<fs::path> roots;
  const char *override_root = std::getenv("MOONSHINE_MODEL_ROOT");
  fs::path dir = override_root != nullptr ? fs::path(override_root)
                                          : fs::current_path();
  for (int up = 0; up < 4; ++up) {
    for (const char *relative :
         {"core/moonshine-tts/data", "test-assets"}) {
      const fs::path candidate = dir / relative;
      if (fs::is_directory(candidate)) {
        roots.push_back(candidate);
      }
    }
    if (!roots.empty()) {
      break;
    }
    dir = dir.parent_path();
  }
  return roots;
}

/// Every .ort under the roots, deduplicated.
///
/// Split-pair halves are included: both are real sessions the library creates,
/// and the weights half is the one holding the dequantisation ops.
std::vector<fs::path> all_ort_models() {
  std::set<fs::path> found;
  for (const fs::path &root : model_roots()) {
    std::error_code ec;
    auto it = fs::recursive_directory_iterator(
        root, fs::directory_options::skip_permission_denied, ec);
    if (ec) {
      continue;
    }
    for (const auto &entry : it) {
      if (entry.is_regular_file(ec) && entry.path().extension() == ".ort") {
        found.insert(fs::canonical(entry.path(), ec));
      }
    }
  }
  return {found.begin(), found.end()};
}

}  // namespace

TEST_CASE("every shipped .ort model creates a session") {
  OrtEnvHandle env;
  REQUIRE(env.env != nullptr);

  const std::vector<fs::path> models = all_ort_models();
  // A silent skip would let a broken minimal build look like a pass, which is
  // the one thing this test exists to prevent.
  REQUIRE_MESSAGE(!models.empty(),
                  "no .ort models found; run from the repository root or set "
                  "MOONSHINE_MODEL_ROOT");
  MESSAGE("sweeping " << models.size() << " models");

  std::vector<std::string> failures;
  for (const fs::path &model : models) {
    const std::string error = session_error(env.env, model);
    if (!error.empty()) {
      failures.push_back(model.filename().string() + ": " + error);
    }
  }
  for (const std::string &failure : failures) {
    MESSAGE(failure);
  }
  CHECK(failures.empty());
}

TEST_CASE("models compiled into the library create a session") {
  OrtEnvHandle env;
  REQUIRE(env.env != nullptr);

  // The voice detector, which is the only model still compiled in. The symbol
  // still says "onnx" but the bytes are .ort; see the header. The diarization
  // models used to be here too and are now a download
  // (docs/diarization-models.md), so the .ort walk above covers them.
  const std::string error =
      session_error_from_memory(env.env, silero_vad_onnx, silero_vad_onnx_len);
  CHECK(error == "");
}

TEST_CASE("a .onnx is refused rather than parsed") {
  OrtEnvHandle env;
  REQUIRE(env.env != nullptr);

  // Not a real model: load_model_format=ORT should reject it on the format,
  // long before anything looks at the contents. This is what a user passing a
  // .onnx hits, and it must behave the same on full and minimal builds.
  const fs::path scratch =
      fs::temp_directory_path() / "moonshine-load-sweep-not-a-model.onnx";
  {
    FILE *f = std::fopen(scratch.c_str(), "wb");
    REQUIRE(f != nullptr);
    std::fputs("not a model", f);
    std::fclose(f);
  }
  const std::string error = session_error(env.env, scratch);
  CHECK(error != "");
  std::error_code ec;
  fs::remove(scratch, ec);
}
