"""Generate the compiled-in VAD data blobs for the moonshine-micro Pico build.

Produces, under ``examples/rp2350/generated/``:

    vad_config.h          -- audio / front-end / segmenter constants (always).
    vad_mel_tables.{h,cc} -- precomputed Hann window + CSR Slaney mel
                             filterbank for the VAD front-end (always).
    vad_model_data.{h,cc} -- the int8 VAD .tflite as a flash byte array (only
                             when a model path is supplied or found under
                             ``models/``).

Run ``--config-only`` to regenerate config + mel tables without a model file.
Pass ``--tflite`` (or rely on the default under ``moonshine-micro/models/``) to also
embed the model.

Usage::

    python vad/scripts/generate_vad_embedded_data.py --config-only
    python vad/scripts/generate_vad_embedded_data.py \\
        --tflite models/tinyvad_cnn_speech_mel_head16.tflite
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import textwrap

# This script lives at moonshine-micro/vad/scripts/.
MOONSHINE_MICRO_ROOT = pathlib.Path(__file__).resolve().parents[2]
REPO_ROOT = MOONSHINE_MICRO_ROOT.parent
for _p in (REPO_ROOT, REPO_ROOT / "scripts", MOONSHINE_MICRO_ROOT / "stt" / "scripts"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from models.log_mel_pure import hann_window, make_mel_filterbank  # noqa: E402
from models.vad_net import (  # noqa: E402
    VAD_F_MIN,
    VAD_F_MAX,
    VAD_HOP,
    VAD_N_FFT,
    VAD_N_MELS,
    VAD_SAMPLE_RATE,
    VAD_WINDOW_FRAMES,
)
# Reuse the byte/float/int array formatters from the spelling generator.
from generate_embedded_data import (  # noqa: E402
    _format_byte_array,
    _format_float32_array,
    _format_plain_int_array,
    _include_guard,
)

# 1 s extraction clip (matches the STT classifier input) and segmenter defaults
# baked into vad_segmenter.{h,cc}.
VAD_CLIP_SECONDS = 1.0
VAD_CLIP_NUM_SAMPLES = int(round(VAD_SAMPLE_RATE * VAD_CLIP_SECONDS))
VAD_THRESHOLD = 0.5
VAD_SMOOTH_DURATION_S = 0.5
VAD_LOOK_BEHIND_SAMPLES = 8192
VAD_MAX_SEGMENT_SECONDS = 15.0


def _smooth_window_frames() -> int:
    import math

    return max(1, int(math.ceil((VAD_SMOOTH_DURATION_S * VAD_SAMPLE_RATE) / VAD_HOP)))


def _write_vad_config(out_dir: pathlib.Path) -> None:
    smooth_frames = _smooth_window_frames()
    max_seg_samples = int(round(VAD_MAX_SEGMENT_SECONDS * VAD_SAMPLE_RATE))
    header = textwrap.dedent(f"""\
        // AUTO-GENERATED by moonshine-micro/vad/scripts/generate_vad_embedded_data.py
        // DO NOT EDIT. Regenerate with:
        //   python moonshine-micro/vad/scripts/generate_vad_embedded_data.py --config-only
        //
        // VAD audio / front-end / segmenter constants. main.cc, vad.cc and
        // vad_segmenter.cc read these instead of hard-coding 32/16/512.

        #ifndef {_include_guard("vad_config")}
        #define {_include_guard("vad_config")}

        namespace spelling {{

        // --- front-end (one mel frame per 32 ms chunk) ---
        constexpr int   kVadSampleRate    = {VAD_SAMPLE_RATE};
        constexpr int   kVadHop           = {VAD_HOP};
        constexpr int   kVadNFft          = {VAD_N_FFT};
        constexpr int   kVadWinLength     = {VAD_N_FFT};
        constexpr int   kVadNMels         = {VAD_N_MELS};
        constexpr int   kVadWindowFrames  = {VAD_WINDOW_FRAMES};
        constexpr int   kVadWindowSamples = {VAD_WINDOW_FRAMES * VAD_HOP};
        constexpr float kVadFMin          = {VAD_F_MIN:.1f}f;
        constexpr float kVadFMax          = {VAD_F_MAX:.1f}f;

        // --- segmenter (moving-average smoother + clip extraction) ---
        constexpr float  kVadThreshold          = {VAD_THRESHOLD:.4f}f;
        constexpr int    kVadSmoothWindowFrames = {smooth_frames};
        constexpr int    kVadLookBehindSamples  = {VAD_LOOK_BEHIND_SAMPLES};
        constexpr int    kVadMaxSegmentSamples  = {max_seg_samples};

        // --- extracted clip handed to the STT classifier (front-aligned 1 s) ---
        constexpr int   kVadClipNumSamples = {VAD_CLIP_NUM_SAMPLES};

        }}  // namespace spelling

        #endif  // {_include_guard("vad_config")}
        """)
    (out_dir / "vad_config.h").write_text(header)
    print(f"  vad_config.h: n_mels={VAD_N_MELS} window_frames={VAD_WINDOW_FRAMES} "
          f"hop={VAD_HOP} smooth_frames={smooth_frames}")


def _write_vad_mel_tables(out_dir: pathlib.Path) -> None:
    n_freq = VAD_N_FFT // 2 + 1
    window = list(hann_window(VAD_N_FFT, periodic=True))
    if len(window) != VAD_N_FFT:
        raise SystemExit("window length != n_fft")
    fb = make_mel_filterbank(n_freq, VAD_N_MELS, VAD_SAMPLE_RATE, VAD_F_MIN, VAD_F_MAX)
    nz_off = [0] * (VAD_N_MELS + 1)
    nz_idx: list[int] = []
    nz_val: list[float] = []
    for m in range(VAD_N_MELS):
        cnt = 0
        for k in range(n_freq):
            v = fb[m][k]
            if v != 0.0:
                nz_idx.append(k)
                nz_val.append(v)
                cnt += 1
        nz_off[m + 1] = nz_off[m] + cnt
    total_nz = nz_off[VAD_N_MELS]

    header = textwrap.dedent(f"""\
        // AUTO-GENERATED by moonshine-micro/scripts/generate_vad_embedded_data.py
        // DO NOT EDIT.
        //
        // Precomputed VAD log-mel front-end tables (periodic Hann window +
        // CSR Slaney mel filterbank). Separate from the spelling mel_tables
        // because the VAD front-end uses n_mels={VAD_N_MELS}, hop={VAD_HOP}.

        #ifndef {_include_guard("vad_mel_tables")}
        #define {_include_guard("vad_mel_tables")}

        namespace spelling {{

        constexpr int kVadMelTableNFft  = {VAD_N_FFT};
        constexpr int kVadMelTableNMels = {VAD_N_MELS};
        constexpr int kVadMelTableNFreq = {n_freq};
        constexpr int kVadMelNzTotal    = {total_nz};

        extern const float kVadMelWindow[kVadMelTableNFft];
        extern const int   kVadMelNzOff[kVadMelTableNMels + 1];
        extern const int   kVadMelNzIdx[kVadMelNzTotal];
        extern const float kVadMelNzVal[kVadMelNzTotal];

        }}  // namespace spelling

        #endif  // {_include_guard("vad_mel_tables")}
        """)
    (out_dir / "vad_mel_tables.h").write_text(header)

    body = textwrap.dedent("""\
        // AUTO-GENERATED by moonshine-micro/scripts/generate_vad_embedded_data.py
        // DO NOT EDIT.

        #include "vad_mel_tables.h"

        namespace spelling {

        const float kVadMelWindow[kVadMelTableNFft] = {
        """)
    body += _format_float32_array(window) + "\n};\n\n"
    body += "const int kVadMelNzOff[kVadMelTableNMels + 1] = {\n"
    body += _format_plain_int_array(nz_off) + "\n};\n\n"
    body += "const int kVadMelNzIdx[kVadMelNzTotal] = {\n"
    body += _format_plain_int_array(nz_idx) + "\n};\n\n"
    body += "const float kVadMelNzVal[kVadMelNzTotal] = {\n"
    body += _format_float32_array(nz_val) + "\n};\n\n"
    body += "}  // namespace spelling\n"
    (out_dir / "vad_mel_tables.cc").write_text(body)
    flash_bytes = 4 * VAD_N_FFT + 4 * (VAD_N_MELS + 1) + 8 * total_nz
    print(f"  vad_mel_tables.{{h,cc}}: window={VAD_N_FFT}, CSR nz={total_nz} "
          f"(~{flash_bytes / 1024:.1f} KB flash)")


def _write_vad_model(out_dir: pathlib.Path, tflite: pathlib.Path) -> None:
    data = tflite.read_bytes()
    header = textwrap.dedent(f"""\
        // AUTO-GENERATED by moonshine-micro/scripts/generate_vad_embedded_data.py
        // DO NOT EDIT.
        //
        // Source: {tflite.relative_to(MOONSHINE_MICRO_ROOT)}
        // Bytes:  {len(data)}

        #ifndef {_include_guard("vad_model_data")}
        #define {_include_guard("vad_model_data")}
        #include <cstdint>

        extern const unsigned int g_vad_model_data_size;
        extern const unsigned char g_vad_model_data[];

        #endif  // {_include_guard("vad_model_data")}
        """)
    (out_dir / "vad_model_data.h").write_text(header)
    body = textwrap.dedent(f"""\
        // AUTO-GENERATED by moonshine-micro/scripts/generate_vad_embedded_data.py
        // DO NOT EDIT.

        #include "vad_model_data.h"

        const unsigned int g_vad_model_data_size = {len(data)};
        alignas(16) const unsigned char g_vad_model_data[] = {{
        """)
    body += _format_byte_array(data) + "\n};\n"
    (out_dir / "vad_model_data.cc").write_text(body)
    print(f"  vad_model_data.{{h,cc}}: {len(data):,} bytes "
          f"({len(data) / 1024:.1f} KiB)")


def _auto_tflite() -> pathlib.Path | None:
    cand = MOONSHINE_MICRO_ROOT / "models" / "tinyvad_cnn_speech_mel_head16.tflite"
    return cand if cand.is_file() else None


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out-dir", default=str(MOONSHINE_MICRO_ROOT / "examples/rp2350/generated"))
    ap.add_argument("--tflite", default=None,
                    help="int8 VAD .tflite to embed (auto-discovered if omitted).")
    ap.add_argument("--config-only", action="store_true",
                    help="Only emit vad_config.h + vad_mel_tables.{h,cc}.")
    args = ap.parse_args(argv)

    out_dir = pathlib.Path(args.out_dir).expanduser()
    if not out_dir.is_absolute():
        out_dir = MOONSHINE_MICRO_ROOT / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Output: {out_dir}/")
    _write_vad_config(out_dir)
    _write_vad_mel_tables(out_dir)

    if args.config_only:
        print("Done (config-only; vad_model_data not emitted).")
        return 0

    tflite = _auto_tflite()
    if args.tflite:
        tflite = pathlib.Path(args.tflite).expanduser()
        if not tflite.is_absolute():
            tflite = MOONSHINE_MICRO_ROOT / tflite
    if tflite is None or not tflite.is_file():
        print("No int8 VAD .tflite found; emitted config + mel tables only.\n"
              "  Pass --tflite (e.g. models/tinyvad_cnn_speech_mel_head16.tflite) "
              "to also embed the model.")
        return 0
    _write_vad_model(out_dir, tflite)
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
