// Generated by tts-voice-level-calibrate. Do not edit.
//
// The peak each voice reaches when it speaks, measured without
// normalization, so streaming can pick a gain before it has any
// audio to measure. See kokoro-voice-levels.h.

#ifndef MOONSHINE_TTS_KOKORO_VOICE_LEVELS_DATA_H
#define MOONSHINE_TTS_KOKORO_VOICE_LEVELS_DATA_H

namespace moonshine_tts {

// Sorted by id so lookup can binary search.
inline constexpr KokoroVoiceLevel kKokoroVoiceLevels[] = {
    {"af_alloy", 0.8020f},      {"af_aoede", 0.9307f},
    {"af_bella", 0.7094f},      {"af_heart", 0.7047f},
    {"af_jessica", 0.8545f},    {"af_kore", 0.7214f},
    {"af_nicole", 0.7588f},     {"af_nova", 0.4052f},
    {"af_river", 0.8370f},      {"af_sarah", 0.8983f},
    {"af_sky", 0.6065f},        {"am_adam", 1.0000f},
    {"am_echo", 0.6935f},       {"am_eric", 0.5456f},
    {"am_fenrir", 1.0000f},     {"am_liam", 0.7088f},
    {"am_michael", 0.7481f},    {"am_onyx", 0.7951f},
    {"am_puck", 1.0000f},       {"am_santa", 0.7471f},
    {"bf_alice", 0.8160f},      {"bf_emma", 0.7148f},
    {"bf_isabella", 1.0000f},   {"bf_lily", 0.6856f},
    {"bm_daniel", 0.7159f},     {"bm_fable", 0.7932f},
    {"bm_george", 0.5630f},     {"bm_lewis", 0.7430f},
    {"ef_dora", 0.7820f},       {"em_alex", 0.6905f},
    {"em_santa", 0.6921f},      {"hf_alpha", 1.0000f},
    {"hf_beta", 0.9907f},       {"hm_omega", 1.0000f},
    {"hm_psi", 1.0000f},        {"jf_alpha", 0.5523f},
    {"jf_gongitsune", 0.6508f}, {"jf_nezumi", 0.6708f},
    {"jf_tebukuro", 0.6508f},   {"jm_kumo", 1.0000f},
    {"pf_dora", 0.7563f},       {"pm_alex", 0.6892f},
    {"pm_santa", 0.6625f},      {"zf_xiaobei", 0.8001f},
    {"zf_xiaoni", 0.8224f},     {"zf_xiaoxiao", 1.0000f},
    {"zf_xiaoyi", 0.5833f},     {"zm_yunjian", 0.7668f},
    {"zm_yunxi", 0.9160f},      {"zm_yunxia", 0.7421f},
    {"zm_yunyang", 1.0000f},
};

}  // namespace moonshine_tts

#endif  // MOONSHINE_TTS_KOKORO_VOICE_LEVELS_DATA_H
