#!/usr/bin/env bash
#
# Guard against banned C++ constructs creeping into first-party core code.
# See core/STYLE_GUIDE.md for the rationale. Runs anywhere (macOS/Linux), needs
# only bash + grep + find, and is registered as the `check-banned-constructs`
# ctest.
#
# Two tiers of enforcement:
#
#   1. Hard ban (zero tolerance, everywhere in first-party code): unsafe C
#      string functions that have safe, bounded replacements.
#
#   2. Baseline gate (regression only): owning new/delete, C allocation calls,
#      reinterpret_cast, and non-standard compiler builtins (__builtin_*, a
#      GCC/Clang extension MSVC rejects) are tolerated where they already exist
#      (recorded in core/.banned-constructs-allowlist) but blocked in any file
#      not on that list. As modules are cleaned up, regenerate the baseline with
#      `scripts/check-banned-constructs.sh --update-baseline` to lock in the
#      improvement.
#
# Usage:
#   scripts/check-banned-constructs.sh                 # check (default)
#   scripts/check-banned-constructs.sh --update-baseline
set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT_DIR="$(dirname "${SCRIPTS_DIR}")"
CORE_DIR="${REPO_ROOT_DIR}/core"
BASELINE_FILE="${CORE_DIR}/.banned-constructs-allowlist"

MODE="check"
if [[ "${1:-}" == "--update-baseline" ]]; then
  MODE="update"
elif [[ -n "${1:-}" ]]; then
  echo "usage: $0 [--update-baseline]" >&2
  exit 2
fi

# Hard-banned everywhere: unsafe C string functions.
HARD_PATTERN='\b(strcpy|strcat|sprintf|vsprintf|gets|strncpy|strncat)[[:space:]]*\('

# Baseline-gated categories (name and regex).
BASELINE_NAMES=(reinterpret_cast c_alloc raw_new_delete compiler_builtin)
BASELINE_PATTERNS=(
  'reinterpret_cast'
  '\b(malloc|calloc|realloc|free)[[:space:]]*\('
  '\b(new|delete)\b'
  # GCC/Clang __builtin_* functions are not standard C++ and fail to compile
  # under MSVC (used for the Windows build). Match calls (trailing paren) so a
  # mention in a comment does not trip the gate. Prefer a portable helper or,
  # if genuinely needed, guard with #ifdef and add the file to the allowlist.
  '__builtin_[A-Za-z0-9_]+[[:space:]]*\('
)

# Collect first-party C/C++ sources, excluding vendored trees, build output,
# and the reliability test tooling (which is not shipped and is exempt).
files=()
while IFS= read -r f; do
  files+=("$f")
done < <(
  find "${CORE_DIR}" \
    \( -path "${CORE_DIR}/third-party" \
       -o -path "${CORE_DIR}/cpp-annote" \
       -o -path "${CORE_DIR}/reliability" \
       -o -name build \) -prune -o \
    -type f \( \
      -name '*.c' -o \
      -name '*.cc' -o \
      -name '*.cpp' -o \
      -name '*.h' -o \
      -name '*.hpp' \
    \) -print
)

# Print repo-relative paths of first-party files matching a regex, sorted.
scan() {
  local pattern="$1"
  if [[ "${#files[@]}" -eq 0 ]]; then
    return 0
  fi
  grep -lE -- "${pattern}" "${files[@]}" 2>/dev/null \
    | sed "s#^${REPO_ROOT_DIR}/##" \
    | LC_ALL=C sort
}

if [[ "${MODE}" == "update" ]]; then
  {
    echo "# Files currently allowed to contain otherwise-banned constructs."
    echo "# Generated by scripts/check-banned-constructs.sh --update-baseline."
    echo "# Format: <category>:<repo-relative-path>. Shrink this list as code is"
    echo "# migrated to safer patterns (see core/STYLE_GUIDE.md)."
    for i in "${!BASELINE_NAMES[@]}"; do
      name="${BASELINE_NAMES[$i]}"
      while IFS= read -r path; do
        [[ -n "${path}" ]] && echo "${name}:${path}"
      done < <(scan "${BASELINE_PATTERNS[$i]}")
    done
  } >"${BASELINE_FILE}"
  echo "Wrote baseline to ${BASELINE_FILE#"${REPO_ROOT_DIR}"/}"
  exit 0
fi

status=0

# Tier 1: hard ban.
hard_hits="$(scan "${HARD_PATTERN}" || true)"
if [[ -n "${hard_hits}" ]]; then
  echo "ERROR: banned unsafe C string function(s) found (use bounded/std alternatives):" >&2
  while IFS= read -r path; do
    echo "  ${path}" >&2
  done <<<"${hard_hits}"
  status=1
fi

# Tier 2: baseline gate.
if [[ ! -f "${BASELINE_FILE}" ]]; then
  echo "ERROR: baseline ${BASELINE_FILE#"${REPO_ROOT_DIR}"/} missing." >&2
  echo "  Generate it with: scripts/check-banned-constructs.sh --update-baseline" >&2
  exit 1
fi

for i in "${!BASELINE_NAMES[@]}"; do
  name="${BASELINE_NAMES[$i]}"
  while IFS= read -r path; do
    [[ -z "${path}" ]] && continue
    if ! grep -qxF "${name}:${path}" "${BASELINE_FILE}"; then
      echo "ERROR: new '${name}' usage in ${path}" >&2
      echo "  This construct is banned in files not already on the baseline." >&2
      echo "  Prefer RAII/containers/std::span (see core/STYLE_GUIDE.md)." >&2
      status=1
    fi
  done < <(scan "${BASELINE_PATTERNS[$i]}")
done

if [[ "${status}" -eq 0 ]]; then
  echo "check-banned-constructs: OK"
fi
exit "${status}"
