#!/usr/bin/env bash
#
# Gate clang-tidy findings against a committed baseline so that only *newly
# introduced* problems fail the reliability run. This mirrors the approach in
# check-banned-constructs.sh: the current first-party code has a known, curated
# set of findings (see core/.clang-tidy-baseline) that are either benign for our
# "C++ as a better C" style or deliberately deferred; we accept those but refuse
# to let new ones creep in.
#
# The baseline key is "<check-name>\t<repo-relative-path>" (not line numbers, so
# it is stable across edits and reformatting). A finding is "new" if that pair is
# absent from the baseline. Adding a genuinely new class of bug -- e.g. the first
# clang-analyzer null-dereference in a file that never had one -- therefore fails
# the run, while shuffling lines around in an already-flagged file does not.
#
# Usage:
#   check-clang-tidy.sh --log FILE --baseline FILE --repo-root DIR [--update]
#
#     --update   Regenerate the baseline from FILE instead of comparing. Use this
#                after intentionally changing the code/config, then commit the
#                updated baseline.
#
# Exit status: 0 = no new findings (or --update succeeded); 1 = new findings;
#              2 = usage / environment error.
set -uo pipefail

LOG=""
BASELINE=""
REPO_ROOT=""
UPDATE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --log)       LOG="$2"; shift 2 ;;
    --baseline)  BASELINE="$2"; shift 2 ;;
    --repo-root) REPO_ROOT="$2"; shift 2 ;;
    --update)    UPDATE=1; shift ;;
    *) echo "check-clang-tidy: unknown argument '$1'" >&2; exit 2 ;;
  esac
done

if [[ -z "${LOG}" || -z "${BASELINE}" || -z "${REPO_ROOT}" ]]; then
  echo "check-clang-tidy: --log, --baseline and --repo-root are required" >&2
  exit 2
fi
if [[ ! -f "${LOG}" ]]; then
  echo "check-clang-tidy: log file '${LOG}' not found" >&2
  exit 2
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "check-clang-tidy: python3 is required to parse clang-tidy output" >&2
  exit 2
fi

# Extract a sorted, de-duplicated list of "<check>\t<relpath>" pairs from a
# clang-tidy log. run-clang-tidy prints one "path:line:col: warning: msg [check]"
# line per finding (a finding in a shared header is repeated once per translation
# unit, which the de-dup collapses); a single line may list several comma-joined
# checks, each of which becomes its own pair.
extract_keys() {
  python3 - "$1" "${REPO_ROOT}" <<'PY'
import re, sys
log_path, repo_root = sys.argv[1], sys.argv[2]
prefix = repo_root.rstrip("/") + "/"
rx = re.compile(r'^(/.+?):\d+:\d+: (?:warning|error): .*? \[([a-zA-Z0-9.,\-]+)\]\s*$')
keys = set()
with open(log_path, errors="replace") as fh:
    for line in fh:
        m = rx.match(line.rstrip("\n"))
        if not m:
            continue
        path, checks = m.group(1), m.group(2)
        rel = path[len(prefix):] if path.startswith(prefix) else path
        for check in checks.split(","):
            check = check.strip()
            if check:
                keys.add(f"{check}\t{rel}")
for k in sorted(keys):
    print(k)
PY
}

CURRENT="$(mktemp)"
trap 'rm -f "${CURRENT}"' EXIT
extract_keys "${LOG}" >"${CURRENT}"
current_count="$(wc -l <"${CURRENT}" | tr -d ' ')"

if [[ "${UPDATE}" == "1" ]]; then
  {
    echo "# clang-tidy baseline for the Moonshine core library."
    echo "#"
    echo "# Auto-generated by scripts/check-clang-tidy.sh --update. Each line is a"
    echo "# known, accepted finding as \"<check-name>\\t<repo-relative-path>\". The"
    echo "# reliability run (scripts/reliability-remote.sh) fails only when clang-tidy"
    echo "# reports a pair that is NOT listed here, i.e. a newly introduced problem."
    echo "#"
    echo "# To refresh after an intentional change, re-run the reliability script with"
    echo "# TIDY_UPDATE_BASELINE=1 and commit the regenerated file."
    cat "${CURRENT}"
  } >"${BASELINE}"
  echo "check-clang-tidy: wrote baseline with ${current_count} known finding pair(s) to ${BASELINE}"
  exit 0
fi

if [[ ! -f "${BASELINE}" ]]; then
  echo "check-clang-tidy: baseline '${BASELINE}' not found; run with --update to create it" >&2
  exit 2
fi

# Strip comments/blank lines from the baseline, then report any current pair that
# is absent from it. comm needs both inputs sorted (extract_keys already sorts).
BASE_KEYS="$(mktemp)"
trap 'rm -f "${CURRENT}" "${BASE_KEYS}"' EXIT
grep -v -e '^#' -e '^[[:space:]]*$' "${BASELINE}" | sort -u >"${BASE_KEYS}"

NEW="$(comm -13 "${BASE_KEYS}" "${CURRENT}")"
if [[ -n "${NEW}" ]]; then
  new_count="$(printf '%s\n' "${NEW}" | grep -c . || true)"
  echo "check-clang-tidy: ${new_count} NEW clang-tidy finding(s) not in the baseline:" >&2
  printf '%s\n' "${NEW}" | sed 's/^/  + /' >&2
  echo "" >&2
  echo "If these are intentional, fix them or refresh the baseline with" >&2
  echo "TIDY_UPDATE_BASELINE=1 and commit core/.clang-tidy-baseline." >&2
  exit 1
fi

echo "check-clang-tidy: no new findings (${current_count} pair(s) all covered by baseline)"
exit 0
