"""Embed 1 s int16 PCM clips for the I2S speaker bring-up test.

Reads ``assets/speaker_test/{a,b,c}.wav`` (16 kHz mono) and writes
``generated/speaker_test_clips.{h,cc}`` for ``moonshine_micro_i2s_audio_test``.

Usage::

    python moonshine-micro/examples/rp2350/scripts/generate_speaker_test_clips.py
"""

from __future__ import annotations

import pathlib
import struct
import sys
import wave

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
RP2350_DIR = SCRIPT_DIR.parent
ASSETS = RP2350_DIR / "assets" / "speaker_test"
OUT_DIR = RP2350_DIR / "generated"
CLIPS = (("a", "a.wav"), ("b", "b.wav"), ("c", "c.wav"))
EXPECTED_RATE = 16000
EXPECTED_SAMPLES = 16000


def _read_pcm(path: pathlib.Path) -> tuple[int, list[int]]:
    with wave.open(str(path), "rb") as wf:
        if wf.getnchannels() != 1:
            raise SystemExit(f"{path}: expected mono")
        if wf.getsampwidth() != 2:
            raise SystemExit(f"{path}: expected 16-bit PCM")
        rate = wf.getframerate()
        if rate != EXPECTED_RATE:
            raise SystemExit(f"{path}: expected {EXPECTED_RATE} Hz, got {rate}")
        n = wf.getnframes()
        if n != EXPECTED_SAMPLES:
            raise SystemExit(
                f"{path}: expected {EXPECTED_SAMPLES} samples, got {n}"
            )
        raw = wf.readframes(n)
    samples = list(struct.unpack(f"<{n}h", raw))
    return rate, samples


def _write_header() -> str:
    return """\
// AUTO-GENERATED by examples/rp2350/scripts/generate_speaker_test_clips.py
// DO NOT EDIT.

#ifndef SPELLING_SPEAKER_TEST_CLIPS_H_
#define SPELLING_SPEAKER_TEST_CLIPS_H_

#include <cstdint>

namespace speaker_test {

struct Clip {
  const char* label;
  int sample_rate;
  int num_samples;
  const int16_t* samples;
};

constexpr int kClipCount = 3;
extern const Clip kClips[kClipCount];

}  // namespace speaker_test

#endif  // SPELLING_SPEAKER_TEST_CLIPS_H_
"""


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    entries: list[tuple[str, int, list[int]]] = []
    for label, name in CLIPS:
        path = ASSETS / name
        if not path.is_file():
            print(f"ERROR: missing {path}", file=sys.stderr)
            return 1
        rate, samples = _read_pcm(path)
        entries.append((label, rate, samples))
        print(f"  {label}: {path.name} ({rate} Hz, {len(samples)} samples)")

    (OUT_DIR / "speaker_test_clips.h").write_text(_write_header())

    body = [
        "// AUTO-GENERATED by examples/rp2350/scripts/generate_speaker_test_clips.py",
        "// DO NOT EDIT.",
        "",
        '#include "speaker_test_clips.h"',
        "",
        "namespace speaker_test {",
        "",
    ]
    for label, rate, samples in entries:
        sym = f"kClip_{label}_pcm"
        body.append(f"alignas(2) const int16_t {sym}[] = {{")
        for i in range(0, len(samples), 12):
            chunk = samples[i : i + 12]
            body.append("  " + ", ".join(str(s) for s in chunk) + ",")
        body.append("};")
        body.append("")
    body.append(f"const Clip kClips[kClipCount] = {{")
    for label, rate, samples in entries:
        body.append(
            f'  {{"{label}", {rate}, {len(samples)}, kClip_{label}_pcm}},'
        )
    body.append("};")
    body.append("")
    body.append("}  // namespace speaker_test")
    body.append("")

    (OUT_DIR / "speaker_test_clips.cc").write_text("\n".join(body))
    print(f"Wrote {OUT_DIR}/speaker_test_clips.h and speaker_test_clips.cc")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
